yarnPath: ".yarn/releases/yarn-berry.js"

initScope: gitpanion

packageExtensions:
  "@commitlint/load@*": 
    dependencies:
      "commitlint-plugin-workspace-scopes": "*"
      "commitlint-plugin-scope-empty-exceptions": "*"